DROP INDEX STUDENTNAME_IDX;

CREATE 
INDEX  STUDENTNAME_IDX
ON student (name);

DROP SEQUENCE classroom_id_seq;

CREATE SEQUENCE classroom_id_seq 
MINVALUE 1
MAXVALUE 100
INCREMENT BY 1
START WITH 1
NOCACHE
NOCYCLE;