--1: Развернуть группу строк информирующую о количестве сотрудников на каждой
--   должности в настоящий момент времени, превращая их значения в столбцы.
SELECT 
    SUM(CASE WHEN JOBNAME = 'PRESIDENT' THEN 1 ELSE 0 END) AS PRESIDENTS,
    SUM(CASE WHEN JOBNAME = 'FINANCIAL DIRECTOR' THEN 1 ELSE 0 END) AS FINANCIAL_DIRECTORS,
    SUM(CASE WHEN JOBNAME = 'MANAGER' THEN 1 ELSE 0 END) AS MANAGERS,
    SUM(CASE WHEN JOBNAME = 'CLERK' THEN 1 ELSE 0 END) AS CLERKS,
    SUM(CASE WHEN JOBNAME = 'DRIVER' THEN 1 ELSE 0 END) AS DRIVERS
FROM CAREER NATURAL JOIN JOB;


--2: Требуется преобразовать строки в столбцы, создавая для каждого значения
--   заданного столбца отдельный столбец.
SELECT
    MAX(CASE WHEN DEPTNAME = 'ACCOUNTING' THEN EMPNAME ELSE NULL END) AS ACCOUNTING,
    MAX(CASE WHEN DEPTNAME = 'OPERATIONS' THEN EMPNAME ELSE NULL END) AS OPERATIONS,
    MAX(CASE WHEN DEPTNAME = 'RESEARCH' THEN EMPNAME ELSE NULL END) AS RESEARCH,
    MAX(CASE WHEN DEPTNAME = 'SALES' THEN EMPNAME ELSE NULL END) AS SALES
FROM 
    (SELECT 
        d.DEPTNAME, 
        e.EMPNAME,
        ROW_NUMBER()OVER(PARTITION BY DEPTNAME ORDER BY EMPNAME) AS RN
    FROM CAREER 
        NATURAL JOIN DEPT d
        NATURAL JOIN EMP e)
GROUP BY RN;


--3: Выполните обратное разворачивание для результирующего множества,
--   полученного в задании 1.
CREATE OR REPLACE VIEW jobs_info AS 
(SELECT J.JOBNO, J.JOBNAME,
    CASE J.JOBNAME
        WHEN 'PRESIDENT' THEN EMP_CNTS.PRESIDENTS
        WHEN 'FINANCIAL DIRECTOR' THEN EMP_CNTS.FINANCIAL_DIRECTORS
        WHEN 'MANAGER' THEN EMP_CNTS.MANAGERS
        WHEN 'CLERK' THEN EMP_CNTS.CLERKS
        WHEN 'DRIVER' THEN EMP_CNTS.DRIVERS
        WHEN 'EXECUTIVE DIRECTOR' THEN EMP_CNTS.EXECUTIVE_DIRECTORS
        WHEN 'SALESMAN' THEN EMP_CNTS.SALESMANS
    END COUNT_BY_JOB
FROM
    (SELECT 
        SUM(CASE WHEN JOBNAME = 'PRESIDENT' THEN 1 ELSE 0 END) AS PRESIDENTS,
        SUM(CASE WHEN JOBNAME = 'FINANCIAL DIRECTOR' THEN 1 ELSE 0 END) AS FINANCIAL_DIRECTORS,
        SUM(CASE WHEN JOBNAME = 'MANAGER' THEN 1 ELSE 0 END) AS MANAGERS,
        SUM(CASE WHEN JOBNAME = 'CLERK' THEN 1 ELSE 0 END) AS CLERKS,
        SUM(CASE WHEN JOBNAME = 'DRIVER' THEN 1 ELSE 0 END) AS DRIVERS,
        SUM(CASE WHEN JOBNAME = 'EXECUTIVE DIRECTOR' THEN 1 ELSE 0 END) AS EXECUTIVE_DIRECTORS,
        SUM(CASE WHEN JOBNAME = 'SALESMAN' THEN 1 ELSE 0 END) AS SALESMANS
    FROM CAREER NATURAL JOIN JOB) EMP_CNTS, (SELECT JOBNO, JOBNAME FROM JOB) J);
    
SELECT JOBNAME, COUNT_BY_JOB FROM jobs_info;
    
    
--4: Составьте запрос, который будет выполнять обратное разворачивание
--   результирующего множества в один столбец.
SELECT
    CASE RN
        WHEN 1 THEN JOBNAME
        WHEN 2 THEN CAST(COUNT_BY_JOB AS CHAR(2))
    END JOBS
FROM 
(SELECT * FROM
(SELECT 
    j.JOBNAME, 
    j.COUNT_BY_JOB,
    ROW_NUMBER() OVER(PARTITION BY j.JOBNO ORDER BY j.JOBNO) AS RN
FROM 
    jobs_info j,
    (SELECT * FROM jobs_info))
WHERE RN < 4);


--5: Составьте запрос, который будет исключать повторяющиеся значения из
--   результирующего множества.
SELECT 
    TO_NUMBER(DECODE(LAG(COUNT_BY_JOB) OVER(ORDER BY COUNT_BY_JOB), COUNT_BY_JOB, NULL, COUNT_BY_JOB)) AS EMPS_COUNT_BY_JOB, 
    JOBNAME
FROM jobs_info;





















